"use client";
import { FormEvent, useState } from "react";
const eventTypes = ["Wedding", "Engagement", "Reception", "Birthday", "Corporate", "Baby Shower", "Anniversary", "Graduation", "Private Party", "Other"];
export default function EnquiryForm() {
  const [form, setForm] = useState({ name: "", email: "", phone: "", city: "", eventType: "", eventDate: "", guestCount: "", budget: "", description: "" });
  const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const change = (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setForm({ ...form, [event.target.name]: event.target.value });
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); try { const response = await fetch("/api/customers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage("Your enquiry is in. Create or sign in to your Celebrio account to complete your requirements and view your dashboard."); setForm({ name: "", email: "", phone: "", city: "", eventType: "", eventDate: "", guestCount: "", budget: "", description: "" }); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to submit your enquiry."); } finally { setLoading(false); } }
  return <section className="w-full py-16"><div className="mx-auto max-w-3xl px-6"><div className="mb-10 text-center"><h2 className="text-3xl font-semibold">Start Planning Your Event</h2><p className="mt-3 text-gray-600">Tell us about the occasion. Your personal portal will take it from there.</p></div><form onSubmit={submit} className="grid gap-6 rounded-2xl border bg-white p-8 shadow-sm md:grid-cols-2"><Field label="Name"><input name="name" required value={form.name} onChange={change} placeholder="Your name" className="field" /></Field><Field label="Email"><input name="email" required type="email" value={form.email} onChange={change} placeholder="you@example.com" className="field" /></Field><Field label="Phone"><input name="phone" required value={form.phone} onChange={change} placeholder="9876543210" className="field" /></Field><Field label="City"><input name="city" required value={form.city} onChange={change} placeholder="Bengaluru" className="field" /></Field><Field label="Event type"><select name="eventType" required value={form.eventType} onChange={change} className="field"><option value="">Select event type</option>{eventTypes.map((type) => <option key={type}>{type}</option>)}</select></Field><Field label="Event date"><input name="eventDate" type="date" required value={form.eventDate} onChange={change} className="field" /></Field><Field label="Estimated guests"><input name="guestCount" type="number" min="1" required value={form.guestCount} onChange={change} placeholder="200" className="field" /></Field><Field label="Estimated budget"><select name="budget" required value={form.budget} onChange={change} className="field"><option value="">Select budget</option><option value="300000">Below ₹5 Lakhs</option><option value="750000">₹5–10 Lakhs</option><option value="1750000">₹10–25 Lakhs</option><option value="3750000">₹25–50 Lakhs</option><option value="6000000">Above ₹50 Lakhs</option></select></Field><div className="md:col-span-2"><label className="mb-2 block text-sm font-medium">Tell us what you have in mind</label><textarea name="description" value={form.description} onChange={change} placeholder="Style, must-haves, accessibility needs or anything else..." className="field min-h-28" /></div>{message && <div className="md:col-span-2 rounded-lg bg-violet-50 p-4 text-sm text-violet-900">{message}</div>}<button type="submit" disabled={loading} className="btn-primary md:col-span-2">{loading ? "Submitting..." : "Submit Enquiry"}</button></form></div></section>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>; }
